@extends('layouts.def')

@section('content')
<div class="row">
        <div class="col-sm-10 col-md-8 col-md-offset-1 col-sm-offset-3">
<hr>1. The customer shall pay the car rental fare as per the applicable rates and payment schedules mentioned on the website of VehiclesOnRent at the time of booking. The customer shall also pay parking charges, toll-charges, service tax, state tax and any other fee or levy presently payable or imposed hereinafter under applicable law/s for availing the car rental services.
<hr>2. All the bookings which are for duration of less than 24 hours will be considered as Hourly bookings and the bookings which are for duration of 24 hours or more will be considered as Daily bookings.

<hr>3. All cancellations to be made against the booking ID provided at the time of booking the car.
For Daily Rentals:
If booking is cancelled within 24 hours of pickup time, rental amount and Loss Damage Waiver charges (if applicable) for one day will be deducted along with 3 % processing fee on rest of the refund amount from the booking amount.
If booking is cancelled at least 24 hours prior to pick up time, no rental will be deducted, only 3% processing fee will be charged on the refund amount.
If booking is cancelled at or after pick up time, no refund will be provided.
 For Hourly Rentals - No refund will be provided in case of hourly rental booking.
<hr>4. The Customer agrees and acknowledges that the use of the services offered by VehiclesOnRent is at the sole risk of the Customer. VehiclesOnRent disclaims all representations and warranties of any kind, whether express or implied as to condition, suitability, quality, merchantability and fitness of the services offered by VehiclesOnRent. The liability of VehiclesOnRent is excluded to the fullest extent permitted by law.
a. the service shall meet Customer requirements; b.the service shall be uninterrupted, timely, secure, or error-free.
<hr>
5. VehiclesOnRent shall not be responsible or liable for any loss or damage, howsoever caused or suffered by the Customer arising out of the use of car rental service offered by VehiclesOnRent or due to the failure of VehiclesOnRent to provide services to the Customer for any reason whatsoever including but not limited to the Customer's non-compliance with the services' recorded voice instructions, malfunction, partial or total failure of any network terminal, data processing system, computer tele-transmission or telecommunications system or other circumstances whether or not beyond the control of VehiclesOnRent or any person or any organization involved in the above mentioned systems.
<hr>6. Without prejudice to the above, VehiclesOnRent shall not be liable for any direct or indirect loss or damage which may be suffered by the Customer as a result of any failure on the part of VehiclesOnRent to provide a taxi to the Customer within any stipulated time even if VehiclesOnRent has agreed to provide the taxi, or even if the Customer has apprised VehiclesOnRent of the possibility of any such loss or damage which would result if the taxi is not provided at all or is not provided within the stipulated time to the Customer
<hr>7. Upon the demand of VehiclesOnRent, the Customer shall indemnify VehiclesOnRent from/ and against/ and in respect of any/ or all liabilities, losses, charges and expenses (including legal fees and costs on a full indemnity basis) claims, demands, actions and proceedings which VehiclesOnRent may incur or sustain directly or indirectly from/ or by any reason of/ or in relation to the use or purposed use of the Services provided by VehiclesOnRent.
<hr>8. VehiclesOnRent is hereby authorized to use the location based information provided by any of the telecommunication companies regarding the use of mobile phone by the Customer for making a taxi booking. However, the location based information will be used only to facilitate and improve the probability of locating a taxi for the Customer
<hr>9. VehiclesOnRent shall be entitled to disclose the particulars of the Customer/s in possession of VehiclesOnRent to all companies controlled by VehiclesOnRent or any of its authorized chauffeurs or any government body as required by the law/ or by directive/ or request from any government body or to any third party deemed fit and proper by VehiclesOnRent, in its absolute discretion.
<hr>10. VehiclesOnRent shall be entitled to terminate any booking at any time without giving any reason or prior notice to the Customer.
<hr>11. VehiclesOnRent encourages all its customers to take full responsibility of their luggage/belongings. In case of any loss, from the taxi during the journey, VehiclesOnRent shall endeavour to locate the lost luggage/belongings on a "best-effort" basis but VehiclesOnRent shall not be held responsible for such loss or damage
<hr>12. If the Customer leaves any luggage/belongings/goods in the taxi or has any complaint in respect of the services or the use of the taxi, the Customer shall make a complaint in writing to VehiclesOnRent within 24 hours from such usage
<hr>13. In case of any dispute arising between the Customer and VehiclesOnRent, the dispute shall be referred to an Arbitrator, appointed by VehiclesOnRent in its sole discretion. The Arbitrator so appointed by VehiclesOnRent shall act in conformity with the Arbitration and Conciliation Act, 1996. The award so passed by the Arbitrator shall be binding upon the Customer as well as VehiclesOnRent. The courts of Delhi, India shall have the sole and exclusive jurisdiction in respect of any matters which may be instituted before any court of law, arising from the use of the services offered by VehiclesOnRent.
<hr>14. VehiclesOnRent shall be entitled to add, vary or amend any or all of these terms and conditions at any time at its sole discretion and the Customer shall be bound by such addition, variation or amendment incorporated/made in these terms and conditions with effect from the date set forth by VehiclesOnRent. The terms and conditions shall be available on VehiclesOnRent's website namely www.VehiclesOnRent.com.
<hr>15. VehiclesOnRent shall be entitled to record all the calls made to the call centre/s of VehiclesOnRent for quality and training purposes.
<hr>16. Vehicles registered with VehiclesOnRent may be continuously tracked by VehiclesOnRent using GPS for security reasons or for reasons deemed fit and proper by VehiclesOnRent.
<hr>17. By logging on the Account Access service on VehiclesOnRent's websites, the User/customer hereby authorizes VehiclesOnRent and its agents to access third party sites, including that of Banks and other payment gateways, designated by them or on their behalf for retrieving requested information. While registering, the User will choose a password and the user is responsible for maintaining the confidentiality of the password and the account. The User is fully responsible for all the activities that may take place whilst using their password or account. It is the duty of the User to notify VehiclesOnRent immediately in writing of any unauthorized use of their password or account or any other breach of security. VehiclesOnRent will not be liable for any loss that may be incurred by the User as a result of unauthorized use of customer's password or account, either with or without his/her knowledge. The User shall not use anyone else's password at any time.
<hr>18. The User shall request VehiclesOnRent for any refund/s against the unutilized or 'no show' cab booking for any reasons within 24 hours from the hour of departure. Any applicable refunds would accordingly be processed as per the defined policies of VehiclesOnRent. No refund would be payable for any requests made after the expiry of 24 hours as mentioned above and all unclaimed amounts for such unutilized or 'no show' booking shall be deemed to have been forfeited.
<hr>19. VehiclesOnRent may send booking confirmation, itinerary information, cancellation, payment confirmation, refund status, schedule change or any such other information relevant for the transaction, via SMS or by voice call on the contact number given by the User at the time of booking; VehiclesOnRent may also contact the User by voice call, SMS or email in case the User couldn't or hasn't concluded the booking, for any reason what so ever or to know the preference of the User for concluding the booking and also to help the User for the booking. The User hereby unconditionally consents that such communications via SMS and/ or voice call by VehiclesOnRent is (a) upon the request and authorization of the User, (b) 'transactional' and not an 'unsolicited commercial communication' as per the guidelines of Telecom Regulation Authority of India (TRAI) and (c) in compliance with the relevant guidelines of TRAI or such other authority in India and abroad. The User will indemnify VehiclesOnRent against all types of losses and damages incurred by VehiclesOnRent due to any action taken by TRAI, Access Providers (as per TRAI regulations) or any other authority due to any erroneous compliant made by the User against VehiclesOnRent with respect to the intimations mentioned above or on account of any wrong number or email id provided by the User for any reason whatsoever.
<hr>20. The User warrants that the User shall abide by all such additional procedures and guidelines, as modified from time to time, with respect to the use of VehiclesOnRent's services. The User further warrants that the User shall comply with all the applicable laws and regulations regarding the services provided by VehiclesOnRent.
<hr>21. Unless explicitly provided by VehiclesOnRent, any specific service or deliverable, obtaining sufficient insurance coverage shall be the obligation/option of the User and VehiclesOnRent shall not accept any claim/s arising out of such contingencies.
<hr>22. Insurance cover, if any provided as a part of the service/ product by VehiclesOnRent shall be based on the terms and conditions of the insuring company. The User shall contact the insurance company directly for any claim/s or dispute/s which may arise out of such insurance cover. VehiclesOnRent shall not provide any express or implied undertakings for acceptance of the claims by the insurance company.
<hr>23. Following conditions will be considered as Myles car misuse. Customers will be fined if found involved in any of the following:

<hr>24. Over speeding: Users are allowed to drive the Vehicle up to a maximum speed of 120 km/hr (74 miles/hr), beyond which the Vehicle will be considered as over speeding. A penalty of Rs. 200 will be charged on the first instance, followed by a further penalty of Rs. 500 and Rs. 1000 for 2nd instance and 3rd instance respectively making it a total of Rs. 1,700/- at third instance. After the third instance, Booking will stand cancelled and the Company shall get the right to take back the Vehicle and terminate this Agreement.
<hr>25. Traffic violation: Customers are liable to pay for any traffic violation tickets received during their journey. VehiclesOnRent can charge traffic violation from the customer’s credit/debit card on actuals if the violations tickets are sent directly to the company by the traffic department.
<hr>26. Car spare part changed: Customers should not change or remove any car spare parts. In case of emergency, the customer should inform VehiclesOnRent and act as per advice. Customers will be charged a penalty of Rs. 5000 over and above the cost of spare part.
<hr>27. Tyre misuse: In case of any tyre damages resulting from driving in bad terrain and continued driving in case of tyre puncture, customers will be charged for the cost of tyre on actuals.
<hr>28. Running vehicle in damaged conditions: Customers are not advised to drive the car if it gets damaged in an accident. Customers are advised to inform VehiclesOnRent immediately. In such case, customers will be charged for the cost of spare parts on actuals.
<hr>29. Unauthorized activity in the car: Customers are not allowed to carry arms, ammunitions and banned drugs. In addition, use of car for commercial activity such as product sell and promotion, and carry goods is strictly prohibited. In such cases, customers will be charged a penalty of Rs. 5000.
<hr>30. External branding: Any form of external branding on the car is prohibited. Customers are not allowed to paste or paint any external brand promotion on the car. Customers will have to pay a penalty of Rs. 5000.
<hr>31. Tampering with devices: Customers are not allowed to tamper with the odometer, GPS device and in-car technology devices. Customers will have to pay a penalty of Rs. 1000 and over in addition to the actual cost of the device.
<hr>32. Deliberately driving the car in water: Customers will be charged for the actual cost of repair and spare parts.
<hr>33. Producing fake and tampered personal documents: Customers will be charged a penalty of Rs. 1000 if found guilty.
<hr>34. Diversion: Customers are not allowed to drive the car into unauthorized or government banned areas. Customers are advised to inform VehiclesOnRent in case they change the course of their trip. All Myles cars are geo-fenced and customers have to pay a penalty Rs. 10,000 if the car trespasses into banned areas, naxal hit areas, international border of republic of India and extreme end of ladakh.
</br></br></br></div>
</div>
@stop